In [1]:
import tensorflow as tf

In [16]:
a = tf.constant(5, name = 'a_const')
b = tf.constant(7, name = 'b_const')
c = tf.constant([9], name = 'c_const')

print(a.shape)
print(c.shape)

()
(1,)


In [17]:
c.numpy()[0]

9

In [20]:
def add(a,b):
    c = tf.add(a,b)
    return c

output = add(a,b)
print(output.numpy())

12


In [21]:
Scalar = tf.constant(2)
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )

print ("Scalar (1 entry):\n %s \n" % Scalar)

print ("Vector (3 entries) :\n %s \n" % Vector)

print ("Matrix (3x3 entries):\n %s \n" % Matrix)

print ("Tensor (3x3x3 entries) :\n %s \n" % Tensor)

Scalar (1 entry):
 tf.Tensor(2, shape=(), dtype=int32) 

Vector (3 entries) :
 tf.Tensor([5 6 2], shape=(3,), dtype=int32) 

Matrix (3x3 entries):
 tf.Tensor(
[[1 2 3]
 [2 3 4]
 [3 4 5]], shape=(3, 3), dtype=int32) 

Tensor (3x3x3 entries) :
 tf.Tensor(
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]], shape=(3, 3, 3), dtype=int32) 



## tf.matmul for matrices, tf.multiply for scalars

In [28]:
a1 = tf.constant([[5,6],[6,7]])
b1 = tf.constant([[10,6],[5,7]])

def multiply(a,b):
    c = tf.matmul(a,b)
    return c

result = multiply(a1,b1)
print(result.numpy())

[[80 72]
 [95 85]]


In [85]:
varA = tf.Variable(5)
varA = tf.add(varA,1)
print(varA)

tf.Tensor(6, shape=(), dtype=int32)
