In [1]:
import torch

In [7]:
weight = torch.tensor(2.0, requires_grad = True)
bias = torch.tensor(-1.0, requires_grad = True)

def forward(x):
    y = (x * weight) + bias
    return y

x = torch.tensor(1.0)
yhat = forward(x)
yhat

tensor(1., grad_fn=<AddBackward0>)

In [10]:
from torch.nn import Linear
# Initial slope and bias randomly initialized, setting of random seed

In [22]:
torch.manual_seed(1)

model = Linear(in_features = 1, out_features = 1)
# number of predictors and number of targets. NOT NUMBER OF ROWS.

print(list(model.parameters()))
# Returns parameters slope and bias

x = torch.tensor([1.0])
yhat = model(x)
print()
print('Prediction : ', yhat)

# The model has not been trained yet

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]

Prediction :  tensor([0.0739], grad_fn=<AddBackward0>)


## Using a class to create custom model

In [23]:
import torch.nn as nn

In [26]:
# Methods from parent class can be accessed in this class
class LR(nn.Module):
    
    def __init__(self, in_size, out_size):
        super(LR, self).__init__() 
        self.linear = nn.Linear(in_size, out_size)
        
    def forward(self, x):
        yhat = self.linear(x)
        return yhat

In [32]:
model = LR(1,1)
model.state_dict() # Returns the weight and bias values as a dictionaryie. parameters of model

OrderedDict([('linear.weight', tensor([[-0.0729]])),
             ('linear.bias', tensor([-0.0900]))])

In [37]:
model.state_dict()['linear.weight'][0] = torch.tensor([0.5533])
model.state_dict()['linear.bias'][0] = torch.tensor([-0.2457])
# Can change parameter values

print(list(model.parameters()))

[Parameter containing:
tensor([[0.5533]], requires_grad=True), Parameter containing:
tensor([-0.2457], requires_grad=True)]


In [11]:
x_val = torch.tensor([0.3])
model.forward(x_val)

tensor([-0.0797], grad_fn=<AddBackward0>)

In [17]:
tsr_a = torch.tensor([4.0], requires_grad = True)
tsr_b = torch.tensor([5.0])

tsr_c = tsr_a + tsr_b
tsr_c

tensor([-1.], grad_fn=<SubBackward0>)